title: Human 'Omics Data Sharing Field Guide
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: Human 'Omics Data Sharing Field Guide
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Guide to all things human 'omics data sharing in Australia."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.17.0

theme_variables:
  privacy_statement_url: https://www.biocommons.org.au/privacy

exclude:
  - README.md

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main
  -
    scope: 
      path: "pages/data_standards"
    values:
      type: data_standards

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
