title: Human 'Omics Data Sharing Field Guide
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: Human 'Omics Data Sharing Field Guide
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Guide to all things human 'omics data sharing in Australia."
# Metadata description of the website

repository: 'mshadbolt/human-omics-data-sharing-field-guide'

remote-theme: ELIXIR-Belgium/elixir-toolkit-theme
theme: elixir-toolkit-theme

theme_variables:
  privacy_statement_url: https://www.biocommons.org.au/privacy
  toc:
    min_headers: 2
    headers: 'h2, h3'
  github_buttons:
    history: false

exclude:
  - README.md
  - [vendor]
  - vendor
  - ruby

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main
  -
    scope: 
      path: "pages/about"
    values:
      sidebar: about
  -
    scope:
      path: "pages/data_standards"
      type: "pages"
    values:
      type: data_standards
  - scope:
      path: "pages/data_repositories"
      type: "pages"
    values:
      type: data_repositories
  - scope:
      path: pages/legal_ethical
      type: "pages"
    values:
      type: legal_ethical

scholar:
  bibliography_template: bib

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
